Feature/change http method
themoment-team/K2-server pull request #236
Opened 2021-12-08 12:19 UTC by dolong2

불편함의 좋아요 증감에 관련된 HTTP메서드를 PUT에서 PATCH로 수정했습니다.

2021-12-08 23:46 UTC, siwony approved these changes
ㅇㅋ @dolong2 변경사항 문서화 후 FE에 알려주세요!

2021-12-08 23:49 UTC, jyeonjyan requested changes
commit 단위 연관된 작업 마다 하새요..

2021-12-08 23:49 UTC, jyeonjyan commented on build.gradle
> +java.sourceCompatibility = JavaVersion.VERSION_11
? 이거 추가한 이유 설명해주세요

2021-12-08 23:49 UTC, jyeonjyan commented on gradle/wrapper/gradle-wrapper.properties
> +zipStorePath=wrapper/dists
????? 이건 또 뭐죠..?

2021-12-09 01:42 UTC, dolong2 commented on build.gradle
> +java.sourceCompatibility = JavaVersion.VERSION_11
저희 코드에는 있었는데 제 로컬에서 지워져서 추가했습니다

2021-12-09 01:58 UTC, jyeonjyan commented on build.gradle
> +java.sourceCompatibility = JavaVersion.VERSION_11
다음부터는 checkout 신경쓰세요

2021-12-09 02:28 UTC, jyeonjyan commented
✅ 빌드성공

2021-12-09 02:28 UTC, jyeonjyan approved these changes

2021-12-09 02:29 UTC, merged