Feature/modelmapper migration
themoment-team/K2-server pull request #263
Opened 2021-12-25 14:45 UTC by jyeonjyan

## 한 일
* modelmapper -> querydsl: 실제개선사례 전체 조회
* `improvementService`: exception 터지는 조건 if 조건으로 처리. (명확히 명시)
* testcode: 기존의 하드코딩 -> `junit5` 메서드를 골고루 활용 함.

## 개선이 필요해 보이는 부분
* Admin 비즈니스 로직 return type 정규화
* TestCode 스타일 정규화 (테스트코드에서 비즈니스 로직을 사용해 변경에 대해 비용이 생김)

## 참고
<img width="550" alt="Screen Shot 2021-12-25 at 11 43 51 PM" src="https://user-images.githubusercontent.com/67095821/147387469-14b79ae4-63a5-4c98-b35f-fd9b259105b6.png">

Exception Handling 부분에 대한 검증 누락.
Admin 로직 개편 | Test 작성 규칙 의논 후 검증 예정.

## 리뷰
* 메서드 명명규칙
* 빠뜨린 주석, 예외 등등

2021-12-25 14:59 UTC, siwony requested changes
수고하셨습니다. 코멘트 확인해주세요

2021-12-25 14:59 UTC, siwony commented on src/main/java/com/moment/the/improvement/service/ImprovementService.java
>      }
NPE가 발생할 수 있는 코드입니다. 물론 이 메서드에서 발생하지 않지만 만약 `adminRepository.findByEmail`에서 null이 발생하면 추후 Improvement 수정/삭제에서 문제가 생길 가능성이 있다고 생각해요 null에 대한 방어가 필요해 보입니다.

2021-12-25 15:03 UTC, jyeonjyan commented on src/main/java/com/moment/the/improvement/service/ImprovementService.java
>      }
저런 하드 코딩이 발생해여 아까 @siwony 님 PR에
`Admin`에 대한 Util method 추가에 대해 `AppUtil` 로 했으면 좋겠다는 의견 남겼습니다.

해당 Util 작업이 마무리 되는대로 사용하여 안전한 코드로 바꾸도록 하겠습니다.

2021-12-25 15:08 UTC, siwony commented on src/main/java/com/moment/the/improvement/service/ImprovementService.java
>      }
알겠습니다. 그러면 새로운 이슈를 만들어 놓고 이슈 생성하도록 하겠습니다.

2021-12-25 15:10 UTC, siwony approved these changes

2021-12-26 23:06 UTC, dolong2 approved these changes
확인했습니다

2021-12-27 00:21 UTC, merged