Refactoring/utils
themoment-team/K2-server pull request #285
Opened 2022-02-05 07:07 UTC by jyeonjyan

## 해결하려는 문제가 무엇인가요?
* x일 동안 x개의 불편함이.. 여기서 제공하는 x일 api가 uncomfortable 도메인에 속한다고 할 수 없다.
* 기존의 `private static method(calculateAfterDate)`는 `final method`의 역할을 하였다. `public static method`로 바꾸어 메소드 로직을 다른 클래스에서 수행할 수 있도록 하였다.

## 어떻게 해결했나요?
* `meta` package를 만들어서 어느 도메인에 단정짓기 어려운 assets를 묶는다.
* Mockito를 사용해서 test가 돌아갈 때 `LocalDate.time()`을 내가 원하는 prefixDate로 mocking 하였다.

## Attachment
<img width="221" alt="Screen Shot 2022-02-05 at 3 58 58 PM" src="https://user-images.githubusercontent.com/67095821/152632215-fbb6b621-94f2-4924-85f9-639a5128dfc9.png">

<img width="800" alt="Screen Shot 2022-02-05 at 4 06 35 PM" src="https://user-images.githubusercontent.com/67095821/152632395-c6182a59-12f0-4996-88d4-cec3d01cb0a2.png">

## 리뷰해주세요 🙇🏻‍♂️
* PR 전체

2022-02-05 10:26 UTC, siwony requested changes
수고하셨습니다. comment확인해주세요!

2022-02-05 10:26 UTC, siwony commented on src/main/java/com/moment/the/meta/controller/MetaController.java
> +@RequestMapping("/meta/v1.3.1/")
기존 API URI 설계할 때 `major-version/domain/....` 형식으로 설계가 되었는데 다른 API URI와 비교하여 일관성이 없어 기존 방식대로 `/v1/meta`와 같은 방식을 사용하는게 어떠한가요?

2022-02-05 10:35 UTC, siwony commented on src/main/java/com/moment/the/meta/service/MetaService.java
> +    public static int calculateAfterDate() {
`getTermProjectStart()`에서 해당 매서드를 사용한다면 calculateAfterDate()메서드를 private하는게 어떤가요?
controller코드를 보니까 `getTermProjectStart()`를 사용하셨기 떄문에 캡슐화를 하면 어떨까 해서 코멘트 남겨요

2022-02-05 10:35 UTC, siwony commented on src/test/java/com/moment/the/meta/controller/MetaControllerTest.java
> +        }
메서드 시그니처에 `throws Exception`이 선언 되어 있어 try catch문이 불필요한 거 같아요
만약 Exception이 해당 구문에서 발생해도 테스트는 성공하게 됩니다.

2022-02-05 10:35 UTC, siwony commented on src/main/java/com/moment/the/meta/controller/MetaController.java
> +    @GetMapping("/term")
`term`이 함축적인 의미를 지닌거 같아 한번에 알아보기 살짝 어려운감이 있는거 같아요!
이 분기 이전에는 dateSinceProjectStart로 이름을 짓었었는데,
 `get-term-project-start`와 같이 풀네임으로 짓는게 어떠한가요?

2022-02-05 14:56 UTC, jyeonjyan commented on src/test/java/com/moment/the/meta/controller/MetaControllerTest.java
> +        }
아 ! try catch 문의 존재 이유는 
Mockito 공식문서에 `.mockStatic()` 메소드를 사용할 때 가급적 `try with resource`문에서 처리했으면 좋겠다는 설명이 있어요.
`catch{}` 는 제거하도록 하겠습니다.

> https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html#static_mocks

2022-02-05 14:57 UTC, jyeonjyan commented on src/main/java/com/moment/the/meta/controller/MetaController.java
> +    @GetMapping("/term")
네이밍을 고민해보겠습니다.

2022-02-05 15:06 UTC, jyeonjyan commented on src/main/java/com/moment/the/meta/service/MetaService.java
> +    public static int calculateAfterDate() {
기존에는 private static 은 final method와 의미가 같아 "내부 클래스에서만 해당 메소드를 사용할 때 사용." 했어요
제 테스트코드에서 `DI한 service method`, `test 내부에서 같은 로직: getTermProjectStart()`를 assertEquals 하여 검증을 해야했고, 그래서 public static으로 외부에서 사용가능하게 해두었어요. (메소드를 테스트에서 재사용하기 위해서)

2022-02-05 15:17 UTC, jyeonjyan commented on src/main/java/com/moment/the/meta/controller/MetaController.java
> +@RequestMapping("/meta/v1.3.1/")
이 부분ㅇ,ㄴ `v1.3.1` 부터 API uri 패턴을 저렇게 할거라서 미리 바꿔두었어요.

2022-02-05 15:38 UTC, siwony commented on src/main/java/com/moment/the/meta/controller/MetaController.java
> +@RequestMapping("/meta/v1.3.1/")
> 이 부분은 `v1.3.1` 부터 API uri 패턴을 저렇게 할거라서 미리 바꿔두었어요.

변경해야 할 이유를 알고 싶어요

저는 url이 자주 변경될 수 있는 네이밍을 피하는게 좋다는 생각이 들어요 
서버 application의 버전이 변경될 때 마다 url이 중구난방으로 변경될 수 있어요
왜냐하면, 기존 api url 형식은 `v메이저-버전/domain/....` 형식으로 되어있어서 서버 애플리케이션이 대대적인 변화가 일어나지 않는 이상 변경되지 않고 일관적입니다. 
하지만, `v1.3.1`부터 `/domain/server-full-version/....` 형식으로 하게 된다면 url설계가 서버 버전에 의존적으로 되어 client에게는 좋지 않은 경험이 될 거 같아요.

2022-02-05 15:39 UTC, siwony commented on src/main/java/com/moment/the/meta/service/MetaService.java
> +    public static int calculateAfterDate() {
이해했습니다.

2022-02-05 15:45 UTC, jyeonjyan commented on src/main/java/com/moment/the/meta/controller/MetaController.java
> +@RequestMapping("/meta/v1.3.1/")
네 좋은 질문인데요.
v1.3.1 이 될지 v1.3.1+가 될지 모르겠는데, 내부적인 회의를 거쳐 추후 운영(신학기)에 배포되는 시점에는 API gateway를 도입할 생각이예요. (저번에 잠깐 이야기가 나왔지만 이참에 RestDocs, Swagger-ui 를 도입하자는 이야기도 나왔고요)

> 서버 버전에 의존적으로 되어 client에게는 좋지 않은 경험이 될 거 같아요.
API gateway 없이는 애초에 client 에서 backend updated api uri 에 대해서 의존적일 수 밖에 없어요. (지금까지 그래왔고요)
결론적으로는 중단된 서버에서 api uri 변경은 그렇게 큰 데미지는 아니라는거죠.

대대적인 레거시 청산 REST, MSA 를 앞두고 있는 가운데 uri 패턴을 `domain/api-version/more` 이렇게 생각해뒀어요. 
확정된건 아니고요. (현재 production level에는 이미 서버가 중단 됐기 때문이죠)

2022-02-05 15:50 UTC, siwony commented on src/main/java/com/moment/the/meta/controller/MetaController.java
> +@RequestMapping("/meta/v1.3.1/")
확인했습니다.

2022-02-05 15:50 UTC, siwony approved these changes

2022-02-06 05:45 UTC, dolong2 approved these changes
확인했습니다

2022-02-06 05:48 UTC, YangSiJun528 approved these changes
확인했어요.

2022-02-09 16:18 UTC, merged